name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report.html
          path: app/build/reports/lint-results-debug.html

# Unit test
  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3

      - name: Run Tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
            name: unit_test_report.html
            path: app/build/reports/tests/testDebugUnitTest/

  # Instrumented test
  instrumented-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run intrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload instrumented test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumented_test_report.html
          path: app/build/reports/androidTests/connected/


  # Sonar Qube Code Analysis
  sonarcloud-code-analysis:
    needs: [instrumented-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: SonarCloud Scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

