name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report.html
          path: app/build/reports/lint-results-debug.html

# Unit test
    unit-test:
      needs: [lint]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch code
          uses: actions/checkout@v3

        - name: Run Tests
          run: ./gradlew test

        - name: Upload test report
          uses: actions/upload-artifact@v3
          with:
              name: unit_test_report.html
              path: app/build/reports/tests/testDebugUnitTest/
